name: Filter tag and branch

on:
  push:
    tags: v*
    branches-ignore:
      - '!master'

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Run ALL TESTS
      run: echo "Run ALL TESTS"
