name: Pull Request

on:
  push: [pull_request]

jobs:
  prepare:
    runs-on: macOS-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  info:
    runs-on: macOS-latest
    needs: prepare
    steps:
    - name: Check condition
      if: "! contains(github.event.head_commit.message, '[gh skip]')"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - name: Show Event
      run: cat ${GITHUB_EVENT_PATH}

  build:
    runs-on: macOS-latest
    needs: prepare
    steps:
    - uses: actions/checkout@master
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      if: "! contains(github.event.head_commit.message, '[gh skip]')"
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
