name: Skip Phrase

on: [pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest
    if: "contains(github.event.pull_request.body, '[please action]')"
    steps:
    - uses: actions/checkout@v1

    - name: Run ALL TESTS
      run: echo "Run ALL TESTS"
